name: Build WASM
on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Checkout emsdk
        uses: actions/checkout@v6
        with:
          submodules: recursive
          repository: emscripten-core/emsdk
          path: emsdk

      - name: Install emsdk
        run: |
          ./emsdk/emsdk install latest
          ./emsdk/emsdk activate latest

      - name: Checkout vcpkg
        uses: actions/checkout@v6
        with:
          repository: xiaozhuai/vcpkg
          submodules: recursive
          path: vcpkg

      - name: Install dependencies
        run: |
          export EMSDK="$(pwd)/emsdk"
          ./vcpkg/bootstrap-vcpkg.sh
          ./vcpkg/vcpkg install --triplet wasm32-emscripten --clean-after-build libwebp
          sudo apt-get install -y ninja-build

      - name: Configure
        run: |
          export EMSDK="$(pwd)/emsdk"
          export VCPKG_ROOT="$(pwd)/vcpkg"
          cmake --preset wasm32-emscripten-release -B build .

      - name: Build
        run: |
          export EMSDK="$(pwd)/emsdk"
          export VCPKG_ROOT="$(pwd)/vcpkg"
          cmake --build build --target all

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: webp-encoder-wasm
          path: dist/webp_encoder.js
          if-no-files-found: error
